name = "EngineersLand"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aa3cb6d164beb22aad1e760d06da12821b55a30398c535a80325eae4913af010"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"

[options]
acceptable-game-versions = ["1.21.1"]
datapack-folder = "datapacks"
