name = "EngineersLand"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "899d98ab268611be088c08594da82bd814efc08d4a35f46fe15b1f12f9fd4dbd"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.234"

[options]
acceptable-game-versions = ["1.21.1"]
datapack-folder = "datapacks"
