name = "EngineersLand"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5f768519fe951d1330ac5712e6d87de9bd3fbb66e56e3d435bb82f5f0ccf02bd"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.234"

[options]
acceptable-game-versions = ["1.21.1"]
datapack-folder = "datapacks"
